views.style.album_isotope_gallery:
  type: views_style
  mapping:
    image:
      type: mapping
      mapping:
        image_field:
          type: string
        title_field:
          type: string
        author_field:
          type: string
        description_field:
          type: string
        url_field:
          type: string
        image_thumbnail_style:
          type: string
        thumbnail_size_tolerance:
          type: integer
        layout:
          type: string
        captions:
          type: boolean
    gallery:
      type: mapping
      mapping:
        width:
          type: string
        columnWidth:
          type: string
        rowHeight:
          type: string
        gutter:
          type: integer
        horizontal:
          type: boolean
        horizontalOrder:
          type: boolean
        fitWidth:
          type: boolean
        border:
          type: boolean
    grouping:
      type: mapping
      mapping:
        grouping_field_1:
          type: string
          nullable: true
        grouping_field_2:
          type: string
          nullable: true
